/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  8453: {
    GuestBook: {
      address: "0x118a4335ce160fe1b616368ee6685af25224f4dd",
      abi: [
        {
          type: "function",
          name: "getEntries",
          inputs: [
            {
              name: "_start",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_count",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "page",
              type: "tuple[]",
              internalType: "struct GuestBook.Entry[]",
              components: [
                {
                  name: "signer",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "message",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "timestamp",
                  type: "uint256",
                  internalType: "uint256",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getEntriesBySigner",
          inputs: [
            {
              name: "_signer",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256[]",
              internalType: "uint256[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getEntry",
          inputs: [
            {
              name: "_index",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "signer",
              type: "address",
              internalType: "address",
            },
            {
              name: "message",
              type: "string",
              internalType: "string",
            },
            {
              name: "timestamp",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getEntryCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "sign",
          inputs: [
            {
              name: "_message",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "Signed",
          inputs: [
            {
              name: "signer",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "index",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "message",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "timestamp",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 44657053,
    },
  },
  31337: {
    GuestBook: {
      address: "0x5fbdb2315678afecb367f032d93f642f64180aa3",
      abi: [
        {
          type: "function",
          name: "getEntries",
          inputs: [
            {
              name: "_start",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_count",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "page",
              type: "tuple[]",
              internalType: "struct GuestBook.Entry[]",
              components: [
                {
                  name: "signer",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "message",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "timestamp",
                  type: "uint256",
                  internalType: "uint256",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getEntriesBySigner",
          inputs: [
            {
              name: "_signer",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256[]",
              internalType: "uint256[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getEntry",
          inputs: [
            {
              name: "_index",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "signer",
              type: "address",
              internalType: "address",
            },
            {
              name: "message",
              type: "string",
              internalType: "string",
            },
            {
              name: "timestamp",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getEntryCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "sign",
          inputs: [
            {
              name: "_message",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "Signed",
          inputs: [
            {
              name: "signer",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "index",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "message",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "timestamp",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 1,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
